import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/contex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className="bg-slate-100">{children}</body>
      </Provider>
    </html>
  );
}
